import 'uno.css';
import '@unocss/reset/normalize.css';
import './theme.css';
import './components/button.css';
import './components/icon.css';
import './components/input.css';
import './components/rate.css';
import './components/dialog.css';
import './components/switch.css';
import './components/radio.css';
import './components/checkbox.css';
import './components/collapse.css';
import './components/tree.css';
import './components/dropdown.css';
import './components/form.css';
import './components/alert.css';
import './components/breadcrumb.css';
import './components/tabs.css'