import 'uno.css';
import '@unocss/reset/normalize.css';
import './theme.css';
import './button.css';
import './icon.css';
import './input.css';
import './rate.css';
import './dialog.css';
import './switch.css';
import './radio.css';
import './checkbox.css';
import './collapse.css';
import './tree.css';
import './dropdown.css';
import './form.css';
import './alert.css'